name = "mysportzstats"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "MATCH"
class_name = "MatchDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchDO"]

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"
